### ISSUE TITLE
liquid-core - use a proper SECRET_KEY

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/setup#7] opened 2017-07-06 10:51 UTC
https://github.com/liquidinvestigations/setup/blob/master/ansible/roles/liquid-core/templates/local.py#L1:
```python
SECRET_KEY = '-- secret key --'
```

**Comment by gabriel-v** [comment] 2017-09-04 14:39
Duplicate of https://github.com/liquidinvestigations/liquidinvestigations/issues/86

**Closed by gabriel-v** 2017-09-04 14:39 UTC
Labels: invalid
